name: infra-apply
on:
  push:
    branches: [ main, master ]
    paths: [ 'envs/**', 'modules/**', 'bootstrap/**', '.github/workflows/**' ]
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type APPLY to run terraform apply'
        required: true
        default: 'APPLY'

concurrency:
  group: infra-apply-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: true

jobs:
  ensure_state_bucket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init (bootstrap)
        working-directory: bootstrap/state-bucket
        run: terraform init
      - name: Ensure state bucket exists (idempotent)
        working-directory: bootstrap/state-bucket
        env:
          TF_VAR_tenancy_ocid:     ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:        ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:      ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_pem:  ${{ secrets.OCI_PRIVATE_KEY_PEM }}
          TF_VAR_region:           ${{ secrets.OCI_REGION }}
          TF_VAR_compartment_ocid: ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_bucket_name:      ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_os_namespace:     ${{ secrets.OS_NAMESPACE }}
        run: terraform apply -input=false -auto-approve

  apply:
    needs: [ensure_state_bucket]
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'APPLY')
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Write backend config (OCI Object Storage)
        working-directory: envs/newsapp
        run: |
          cat > backend.oci.hcl <<'EOF'
          bucket    = "${{ secrets.TF_STATE_BUCKET }}"
          namespace = "${{ secrets.OS_NAMESPACE }}"
          region    = "${{ secrets.OCI_REGION }}"
          key       = "${{ secrets.TF_STATE_KEY || 'newsapp.tfstate' }}"
          EOF

      - name: Terraform Init (OCI backend)
        working-directory: envs/newsapp
        env:
          OCI_tenancy_ocid:     ${{ secrets.OCI_TENANCY_OCID }}
          OCI_user_ocid:        ${{ secrets.OCI_USER_OCID }}
          OCI_fingerprint:      ${{ secrets.OCI_FINGERPRINT }}
          OCI_region:           ${{ secrets.OCI_REGION }}
          OCI_private_key:      ${{ secrets.OCI_PRIVATE_KEY_PEM }}
        run: terraform init -backend-config=backend.oci.hcl

      - name: Terraform Apply
        working-directory: envs/newsapp
        env:
          TF_VAR_tenancy_ocid:               ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_user_ocid:                  ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint:                ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_pem:            ${{ secrets.OCI_PRIVATE_KEY_PEM }}

          TF_VAR_region:                     ${{ secrets.OCI_REGION }}
          TF_VAR_availability_domain_number: ${{ secrets.AVAILABILITY_DOMAIN_NUMBER }}
          TF_VAR_fault_domain:               ${{ secrets.FAULT_DOMAIN }}

          TF_VAR_compartment_ocid:           ${{ secrets.COMPARTMENT_OCID }}
          TF_VAR_network_compartment_ocid:   ${{ secrets.NETWORK_COMPARTMENT_OCID }}

          TF_VAR_image_ocid:                 ${{ secrets.IMAGE_OCID }}
          TF_VAR_ssh_public_key:             ${{ secrets.SSH_PUBLIC_KEY }}

          TF_VAR_ocpus:                      ${{ vars.NODE_OCPUS || 1 }}
          TF_VAR_memory_gb:                  ${{ vars.NODE_MEMORY_GB || 6 }}
        run: terraform apply -input=false -auto-approve

      - name: Capture Terraform outputs (JSON + summary)
        working-directory: envs/newsapp
        run: |
          terraform output -json > tf-outputs.json
          echo "## Provisioned outputs" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat tf-outputs.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload outputs artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-outputs
          path: envs/newsapp/tf-outputs.json
